version: "3"
services:
  master:
    image: postgres
    tty: true
    volumes:
      - "./docker/master/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
  standby1:
    image: postgres
    tty: true
    depends_on:
      - master
  standby2:
    image: postgres
    tty: true
    depends_on:
      - master
  client:
    image: postgres
    entrypoint: bash
    tty: true
    depends_on:
      - standby1
      - standby2
